import Tests.FixedIssues.Issue1
import Tests.FixedIssues.Issue2
import Tests.FixedIssues.Issue3
import Tests.FixedIssues.Issue4
import Tests.FixedIssues.Issue5
import Tests.FixedIssues.Issue6
import Tests.FixedIssues.Issue7
import Tests.FixedIssues.Issue8
import Tests.FixedIssues.Issue9
import Tests.FixedIssues.Issue10
import Tests.FixedIssues.Issue11
import Tests.FixedIssues.Issue12
import Tests.FixedIssues.Issue14
import Tests.FixedIssues.Issue15
import Tests.FixedIssues.Issue16
import Tests.FixedIssues.Issue17
import Tests.FixedIssues.Issue18
import Tests.FixedIssues.Issue19
import Tests.FixedIssues.Issue20
import Tests.FixedIssues.Issue21
import Tests.FixedIssues.Issue22
import Tests.FixedIssues.Issue23
import Tests.FixedIssues.Issue24
import Tests.FixedIssues.Issue25
import Tests.FixedIssues.Issue26
import Tests.FixedIssues.Issue27
import Tests.FixedIssues.Issue28
import Tests.FixedIssues.Issue29
import Tests.FixedIssues.Issue30
import Tests.FixedIssues.Issue31
import Tests.FixedIssues.Issue32
import Tests.FixedIssues.Issue33
